clear;
close all;
clc;

% load timeLine.mat;
load hrs_horizon.mat;
load wellLogs.mat;

basePath = 'E:/HRS projects/GEO_POST/';

GShowProfileParam = bsCreateGShowProfileParam();
GInvParam = bsCreateGInvParam('poststack');
GSegyInfo = bsCreateGSegyInfo();
GShowProfileParam.showWellFiltCoef = 0.4; % filter coeficient for displaying color wells in profile

GInvParam.dt = 1;    
GInvParam.upNum = 80;
GInvParam.downNum = 50;
GInvParam.indexInWellData.ip = 1;
GInvParam.indexInWellData.time = 2;
GInvParam.usedTimeLineId = 2;
GInvParam.isParallel = 0;
GInvParam.isPrintBySavingFile = 0;
GInvParam.postSeisData.segyInfo = GSegyInfo;
GInvParam.postSeisData.fileName = [basePath, '/seismic/phase_shift_90.sgy'];

% sprintf('%s/seismic/seismic.sgy', basePath);

GSegyInfo.inlineId = 9;
GSegyInfo.crossId = 21;
GSegyInfo.t0 = 0;

validRange = [1 1e10];

% Get inline and crossline of a profile crossing several wells
[inIds, crossIds] = bsGetCDPsByRange([1:142], [1:110]);

highName = [basePath, '\sgy_results\0111SMIResult_wellnumber15.sgy'];
lowName1 = [basePath, '\sgy_results\Ip-DLSR_01_16 (gamma=0.3 sparsity=1)-NLM_2020_01_16 _inline_[1_142]_crossline_[1_110].sgy'];
% lowName = [basePath, '\sgy_results\Ip_DLSR (gamma=0.4 sparsity=2)_inline_[1_142]_crossline_[1_110].sgy'];
outFileName1 = [basePath, '\sgy_results\Mixed1.sgy'];
lowName2 = [basePath, '\sgy_results\Ip-LFC_01_16-NLM_2020_01_16 _inline_[1_142]_crossline_[1_110].sgy'];
outFileName2 = [basePath, '\sgy_results\Mixed2.sgy'];

fs1 = 50;
fs2 = 60;

bsMixTwoResults(lowName1, highName, outFileName1, GSegyInfo, ...
    inIds, crossIds, timeLine{1}, timeLine{3}, GInvParam.dt, validRange, fs1, fs2);

bsMixTwoResults(lowName2, highName, outFileName2, GSegyInfo, ...
    inIds, crossIds, timeLine{1}, timeLine{3}, GInvParam.dt, validRange, fs1, fs2);

methods = {
    
    struct(...
        'name', 'ChenTing result', ...
        'load', struct(...
            'mode', 'segy', ...
            'fileName', highName, ...
            'segyInfo', GSegyInfo ...
        )...
    );...
    
    struct(...
        'name', 'Sparse Impulse', ...
        'isSaveMat', 0, ...
        'load', struct(...
            'mode', 'segy', ...
            'fileName', [basePath, '\inv_result\geoeast_impedance_sparse_impulse_bgp.sgy'], ...
            'segyInfo', bsSetFields(GSegyInfo, {'inlineId', 189; 'crossId', 21; 't0', 780}) ...
        )...
    );...
    
    struct(...
        'name', 'DLSR inversion result', ...
        'load', struct(...
            'mode', 'segy', ...
            'fileName', lowName1, ...
            'segyInfo', GSegyInfo ...
        )...
    );...
  
    struct(...
        'name', 'LFC', ...
        'load', struct(...
            'mode', 'segy', ...
            'fileName', lowName2, ...
            'segyInfo', GSegyInfo ...
        )...
    );...
    
    
    struct(...
        'name', 'Mixed by DLSR', ...
        'showFiltCoef', 1, ...
        'load', struct(...
            'mode', 'segy', ...
            'fileName', outFileName1, ...
            'segyInfo', GSegyInfo ...
        )...
    );...
    
    struct(...
        'name', 'Mixed with LFC', ...
        'showFiltCoef', 1, ...
        'load', struct(...
            'mode', 'segy', ...
            'fileName', outFileName2, ...
            'segyInfo', GSegyInfo ...
        )...
    );...
    
    
};

% [inIds, crossIds] = bsGetProfileCrossingWells(GInvParam, wellLogs(1), ...
%     'isAlongCrossline', 1);
[inIds, crossIds] = bsGetProfileCrossingWells(GInvParam, wellLogs([23, 21, 18, 53, 80, 75]), ...
    'isAlongCrossline', 0);
invResults = bsPostInvTrueMultiTraces(GInvParam, inIds, crossIds, timeLine, methods);

NLMResults = invResults;
NLMResults([5, 6]) = bsNLMInvResults(invResults([5, 6]), [], ...
    'searchOffset', 4, 'windowSize', [2, 4], 'nPointsUsed', 4, ...
    'stride', [1, 1, 1], 'searchStride', [1, 1, 1] ...
);

GShowProfileParam.range.ip = [5800 7900];
GShowProfileParam.range.seismic = [-3 3]*1e4;
GShowProfileParam.colormap.allTheSame = bsGetColormap('original');
GShowProfileParam.isColorReverse = 0;

GShowProfileParam.scaleFactor = 2;
GShowProfileParam.showWellOffset = 1;
GShowProfileParam.plotParam.fontsize = 11;
GShowProfileParam.showPartVert.mode = 'in_2_horizons';
GShowProfileParam.showPartVert.horizonIds = [1, 3];
GShowProfileParam.isShowHorizon = 0;

bsShowInvProfiles(GInvParam, GShowProfileParam, NLMResults, wellLogs, timeLine);
set(gcf, 'position', [ 96          54        1672         780]);