testCommonCode;

GInvParam.isParallel = 1;
GInvParam.isPrintBySavingFile = 0;
ids = bsGetIdsFromWelllogs(wellLogs, {'W1-2201', 'W1-2132', 'W1-2113', 'W2-2024',...
    'W2-2013', 'W3-1931', 'W3-1833'});
% ids = [23, 21, 18, 53, 80, 75];
[inIds, crossIds] = bsGetProfileCrossingWells(GInvParam, wellLogs(ids), ...
    'isAlongCrossline', 1);

% build synthetic data
[synWellLogs, dataIndex, type] = bsGetErrorOfWelllog(GInvParam, timeLine, wellLogs);

r_ids = bsGetIdsFromWelllogs(synWellLogs, {'W2-2024'});
% r_ids = [];
train_ids = setdiff(1:length(synWellLogs), r_ids);

GTrainDICParam = bsCreateGTrainDICParam(...
    'csr', ...
    'title', 'error', ...
    'sizeAtom', 80, ...
    'sparsity', 5, ...
    'nAtom', 5000, ...
    'filtCoef', 1);
GTrainDICParam.isNormalize = 0;

[DIC, train_ids] = bsTrainDics(GTrainDICParam, synWellLogs, train_ids, ...
    [ dataIndex-2, dataIndex], 1);


GSynSparse = bsCreateGSparseInvParam(DIC, 'csr', 'sparsity', 5);

[~, ~, ~, dstFileNames, segyInfo] ...
    = bsPostBuildSynData(GInvParam, GSynSparse, timeLine, ...
    'inIds', inIds, ...
    'crossIds', crossIds, ...
    'gamma', 1, ...
    'isRebuild', 1 ...
    );
realData = bsReadTracesByIdsAndTimeLine(GInvParam.postSeisData.fileName, ...
    GInvParam.postSeisData.segyInfo, inIds, crossIds, ...
    timeLine{GInvParam.usedTimeLineId}, GInvParam.upNum, GInvParam.downNum, GInvParam.dt);

synData = bsReadTracesByIdsAndTimeLine(dstFileNames{1}, segyInfo, inIds, crossIds, ...
            timeLine{GInvParam.usedTimeLineId}, GInvParam.upNum, GInvParam.downNum, GInvParam.dt);
        
synData = bsNLMByRef(synData, realData);
    
[wellPos, wellIndex, wellNames] = bsFindWellLocation(synWellLogs, inIds, crossIds);

tmpWellLog = synWellLogs(wellIndex);

for i = 1:length(wellPos)
    index = wellIndex(i);

    tmpWellLog{i}.wellLog = [tmpWellLog{i}.wellLog, synData(1:end-1, wellPos(i))];
end

bsShowWellLogs(tmpWellLog, [-2, -1, 1]+dataIndex, ...
    {'Real', 'Syn From DIC', 'Syn From True'}, ...
    'colors', {'k', 'r', 'b'}, ...
    'isNormal', 0, ...
    'range', [-2 2]*1e4 ...
);        