testCommonCode;

GInvParam.isParallel = 1;
GInvParam.isPrintBySavingFile = 0;

rangeInline = [1, 142];
rangeCrossline = [1, 110];
[inIds, crossIds] = bsGetCDPsByRange(rangeInline, rangeCrossline);

csrGamma = 0.8;
filtCoef = 0.5;


% 23, 21, 18, 53, 80, 75
% 53, 81
% 50 80
% [inIds, crossIds] = bsGetProfileCrossingWells(GInvParam, wellLogs([23, 21, 18, 53, 80, 75]), 'isAlongCrossline', 0);

% [~, ~, GInvParam, data] = bsBuildInitModel(GInvParam, timeLine, wellLogs, ...
%     'title', 'volume', ...
%     'inIds', inIds, ...
%     'filtCoef', 0.1, ...
%     'crossIds', crossIds, ...
%     'isRebuild', 0, ...
%     'p', 2, ...
%     'nPointsUsed', 10 ...
% );


    
%% 得到每一个井的反演结果
methods = {
    struct(...
        'name', '地震数据', ...
        'type', 'Seismic', ...
        'load', struct(...
            'mode', 'segy', ...
            'fileName', [basePath, '/seismic/phase_shift_90.sgy'], ...
            'segyInfo', bsSetFields(GSegyInfo, {'inlineId', 9; 'crossId', 21; 't0', 0; 'isNegative', 0}) ...
        )...
    );...

    struct(...
        'name', '稀疏脉冲', ...
        'isSaveMat', 0, ...
        'load', struct(...
            'mode', 'segy', ...
            'fileName', [basePath, '\inv_result\geoeast_impedance_sparse_impulse_bgp.sgy'], ...
            'segyInfo', bsSetFields(GSegyInfo, {'inlineId', 189; 'crossId', 21; 't0', 780}) ...
        )...
    );...
    
    struct(...
        'name', '20200330-字典反演结果', ...
        'flag', 'DLSR', ...
        'regParam', struct('lambda', 2, 'gamma', 0.1), ...
        'parampkgs', bsSetFields(GSparseInvParam, {'sparsity', 2}), ...
        'options', bsSetFields(GInvParam.seisInvOptions, ...
            {'maxIter', 10; 'innerIter', 5; 'initRegParam', 0.2}), ...
        'showFiltCoef', 0.8, ...
        'isSaveSegy', 1, ...
        'load', struct(...
            'mode', 'segy', ...
            'segyInfo', GSegyInfo, ...
            'fileName', '' ...
        )...
    );
    
%     struct(...
%         'name', '普通方法', ...
%         'flag', 'LFC', ...
%         'regParam', 0.2, ...
%         'parampkgs', [], ...
%         'options', bsSetFields(GInvParam.seisInvOptions, {'maxIter', 50;}), ...
%         'showFiltCoef', 0.2, ...
%         'isSaveSegy', 1, ...
%         'load', struct(...
%             'mode', 'segy', ...
%             'segyInfo', GSegyInfo, ...
%             'fileName', '' ...
%         )...
%     ); 
};



%% 得到初步的反演结果
fprintf('反演剖面中...\n');
invResults = bsPostInvTrueMultiTraces(GInvParam, inIds, crossIds, timeLine, methods);
finalResults = invResults;
nRes = length(invResults);

% r_ids = bsGetIdsFromWelllogs(wellLogs, {'W1-2113', 'W2-2013', 'W3-1931'});
trainNum = 104;
% mode = 'full_freq';     
mode = 'low_high';
LFs = [60 70 80 90];
% LFs = 60;
sparsity = 2;
iCase = 1;
    

%% 联合字典稀疏重构
for iDIC = 1 : 2
    switch  iDIC
        case 1
            GTrainDICParam = bsCreateGTrainDICParam(...
                'csr', ...
                'feature_reduction', 1, ...
                'normalizationMode', 'feat_max_min', ...
                'isAddTimeInfo', 1, ...
                'isAddLocInfo', 1, ...
                'title', 'HLF', ...
                'sizeAtom', 90, ...
                'sparsity', 5, ...
                'iterNum', 5, ...
                'nAtom', 2000, ...
                'filtCoef', 1, ....
                'isRebuild', 1);
        case 2
            GTrainDICParam = bsCreateGTrainDICParam(...
                'csr', ...
                'feature_reduction', 1, ...
                'normalizationMode', 'feat_max_min', ...
                'isAddTimeInfo', 1, ...
                'isAddLocInfo', 1, ...
                'title', 'HLF', ...
                'sizeAtom', 100, ...
                'sparsity', 5, ...
                'iterNum', 5, ...
                'nAtom', 2000, ...
                'filtCoef', 1, ...
                'isRebuild', 1);
            
    end
    
    for i = 1 : length(LFs)
        finalResults{nRes + iCase} = bsPostRebuildByCSRWithWholeProcess(GInvParam, timeLine, wellLogs, ...
            methods(nRes), invResults{nRes}, sprintf('20200330-联合字典稀疏重构-iDIC-%d-LF-%d', iDIC, LFs(i)), ...
            'gamma', csrGamma, ...
            'trainNum', trainNum, ...
            'wellFiltCoef', GInvParam.initModel.filtCoef, ...
            'mode', mode, ...
            'lowCut', LFs(i)/500, ...
            'highCut', 0.5, ...
            'GTrainDICParam', GTrainDICParam, ...
            'sparsity', sparsity);
        iCase = iCase + 1;
    end
end

return;

%% 画图
% GShowProfileParam.range.seismic = [-1.5 1.5]*1e4;
% % GShowProfileParam.range.ip = [5800 7700];

GShowProfileParam.range.ip = [5800 7600];
% GShowProfileParam.range.ip = [6100 7600];
GShowProfileParam.range.seismic = [-3 3]*1e4;
% GShowProfileParam.colormap.allTheSame = bsGetColormap('original');
GShowProfileParam.colormap.allTheSame = bsGetColormap('velocity');
GShowProfileParam.isColorReverse = 0;
GShowProfileParam.plotParam.fontname = '宋体';
GShowProfileParam.plotParam.fontsize = 11;
GShowProfileParam.scaleFactor = 4;
GShowProfileParam.showWellOffset = 1;
GShowProfileParam.plotParam.fontsize = 10;
GShowProfileParam.showPartVert.upTime = 40;
GShowProfileParam.showPartVert.downTime = 50;
GShowProfileParam.showPartVert.mode = 'up_down_time';

% GShowProfileParam.showPartVert.mode = 'in_2_horizons';
% GShowProfileParam.showPartVert.horizonIds = [1, 2];
% GShowProfileParam.showPartVert.mode = 'off';
GShowProfileParam.isShowColorWells = 1;
GShowProfileParam.isShowWellNames = 1;

GShowProfileParam.isShowHorizon = 0;

for i = 1 : length(finalResults)
    finalResults{i}.showFiltCoef = 1;
end

GShowProfileParam.showWellFiltCoef = 0.5;

bsShowInvProfiles(GInvParam, GShowProfileParam, finalResults, wellLogs, timeLine);
set(gcf, 'position', [ 16          54        1653         570]);

% NLMResults = finalResults;
% NLMResults(nRes-1:end) = bsNLMInvResults(NLMResults(nRes-1:end), [], ...
%         'searchOffset', 2, 'windowSize', [1, 3], 'nPointsUsed', 3, ...
%     'stride', [1, 1, 1], 'searchStride', [1, 1, 1] ...
%     );
% bsShowInvProfiles(GInvParam, GShowProfileParam, NLMResults, wellLogs, timeLine);
% set(gcf, 'position', [ 16          54        1653         739]);
