testCommonCode;

GInvParam.isParallel = 1;
GInvParam.isPrintBySavingFile = 0;
% ids = bsGetIdsFromWelllogs(wellLogs, {'SH8.dat', 'Y128.dat', 'Y196.dat', 'Y172.dat', 'SH13.dat'});
ids = [23, 21, 18, 53, 80, 75];
[inIds, crossIds] = bsGetProfileCrossingWells(GInvParam, wellLogs(ids), ...
    'isAlongCrossline', 1);

[~, ~, GInvParam, data] = bsBuildInitModel(GInvParam, timeLine, wellLogs, ...
    'title', 'test', ...
    'isRebuild', 1, ...
    'p', 1.2, ...
    'nPointsUsed', 14, ...
    'inIds', inIds, ...
    'crossIds', crossIds ...
);

% build synthetic data
[synWellLogs, dataIndex, type] = bsGetErrorOfWelllog(GInvParam, timeLine, wellLogs);

% r_ids = bsGetIdsFromWelllogs(synWellLogs, {'SH8.dat', 'Y196.dat', 'SH13.dat'});
r_ids = [];
e_ids = setdiff(1:length(synWellLogs), r_ids);

[~, ~, ~, dstFileNames, sgyInfo] = bsBuildInitModel(GInvParam, timeLine, synWellLogs(e_ids), ...
    'title', 'test', ...
    'isRebuild', 1, ...
    'p', 2, ...
    'nPointsUsed', 14, ...
    'dataIndex', dataIndex, ...
    'type', type, ...
    'inIds', inIds, ...
    'crossIds', crossIds, ...
    'filtCoef', 1 ...
);
GInvParam.errorModel.fileName = dstFileNames{1};
GInvParam.errorModel.segyInfo = sgyInfo;
GInvParam.errorModel.isUse = 1;

realData = bsReadTracesByIdsAndTimeLine(GInvParam.postSeisData.fileName, ...
    GInvParam.postSeisData.segyInfo, inIds, crossIds, ...
    timeLine{GInvParam.usedTimeLineId}, GInvParam.upNum, GInvParam.downNum, GInvParam.dt);

if GInvParam.errorModel.isUse
    errorData = bsReadTracesByIdsAndTimeLine(dstFileNames{1}, sgyInfo, inIds, crossIds, ...
            timeLine{GInvParam.usedTimeLineId}, GInvParam.upNum, GInvParam.downNum, GInvParam.dt);
else
    errorData = zeros(GInvParam.upNum+GInvParam.downNum, length(inIds));
end
    
    
methods = {
    
    struct(...
        'name', 'Original Seismic', ...
        'type', 'Seismic', ...
        'load', struct(...
            'mode', 'assign', ...
            'data', realData ...
        )...
    );...

    
    struct(...
        'name', 'Input seismic', ...
        'type', 'Seismic', ...
        'load', struct(...
            'mode', 'assign', ...
            'data', realData-errorData ...
        )...
    );...
    
    struct(...
        'name', 'Sparse Impulse', ...
        'isSaveMat', 0, ...
        'load', struct(...
            'mode', 'segy', ...
            'fileName', [basePath, '\inv_result\geoeast_impedance_sparse_impulse_bgp.sgy'], ...
            'segyInfo', bsSetFields(GSegyInfo, {'inlineId', 189; 'crossId', 21; 't0', 780}) ...
        )...
    );...
    
    struct(...
        'name', 'DLSR (gamma=0.25)', ...
        'flag', 'DLSR', ...
        'regParam', struct('lambda', 0.8, 'gamma', 0.25), ...
        'parampkgs', GSparseInvParam, ...
        'options', bsSetFields(GInvParam.seisInvOptions, ...
            {'maxIter', 5; 'innerIter', 40; 'initRegParam', 0.05}), ...
        'showFiltCoef', 1, ...
        'load', struct(...
            'mode', 'off', ...
            'fileName', '' ...
        )...
    );

    struct(...
        'name', 'Error model', ...
        'type', 'Seismic', ...
        'load', struct(...
            'mode', 'assign', ...
            'data', errorData ...
        )...
    );...
};

invResults = bsPostInvTrueMultiTraces(GInvParam, inIds, crossIds, timeLine, methods);

NLMResults = invResults;
NLMResults(3:end-1) = bsNLMInvResults(invResults(3:end-1), invResults{1}.data, ...
    'searchOffset', 4, 'windowSize', 5, 'nPointsUsed', 4, ...
    'stride', [1, 1, 1], 'searchStride', [1, 1, 1] ...
);

GShowProfileParam.showLeftTrNumByWells = 1000;
GShowProfileParam.showRightTrNumByWells = 1000;
GShowProfileParam.range.ip = [6000 7800];
GShowProfileParam.range.seismic = [-3 3]*1e4;
GShowProfileParam.colormap.allTheSame = bsGetColormap('velocity');
GShowProfileParam.isColorReverse = 1;

GShowProfileParam.scaleFactor = 5;
GShowProfileParam.showWellOffset = 1;
GShowProfileParam.plotParam.fontsize = 11;
% GShowProfileParam.showPartVert.upTime = 5;
% GShowProfileParam.showPartVert.downTime = 120;
% GShowProfileParam.showPartVert.mode = 'up_down_time';
% GShowProfileParam.showPartVert.mode = 'in_2_horizons';
% GShowProfileParam.showPartVert.horizonIds = [1, 2];

GShowProfileParam.isShowHorizon = 0;
bsShowInvProfiles(GInvParam, GShowProfileParam, NLMResults, wellLogs, timeLine);
set(gcf, 'position', [  96          54        1717         882]);
